### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Imagica** [farmatholin/SegmentIoBundle#12]
My code QA tool is getting cranky with using "dev-master" version.

If this is stable can you give it a version number?

**Comment by farmatholin** [comment]
Ok. Tomorrow morning

**Comment by Imagica** [comment]
Brilliant, thanks!

**Comment by farmatholin** [comment]
@Imagica 
https://packagist.org/packages/farmatholin/segment-io-bundle#1.2.1
