### ISSUE TITLE
batch_size option to be deprecated soon in Analytics segment configuration options 

### ISSUE THREAD

**Issue by RamyHakam** [farmatholin/SegmentIoBundle#19]
While using the bundle, I got this Warning Continually and it consumes the logs 
**`WARNING: batch_size option to be depricated soon, please use new option flush_at`**

After some investigation, I found that `batch_size` is deprecated and replaced by 'flush_at'   in segment PHP

**Comment by farmatholin** [comment]
Merge pull request with fixes
