### ISSUE TITLE
exception thrown with latest update

### ISSUE THREAD

**Issue by djardine** [farmatholin/SegmentIoBundle#7]
I'm running Symfony 2.7.x

FatalThrowableError in AnnotationListener.php line 51:
Type error: Argument 1 passed to Farmatholin\SegmentIoBundle\EventListener\AnnotationListener::__construct() must be an instance of Doctrine\Common\Annotations\CachedReader, instance of Doctrine\Common\Annotations\FileCacheReader given, called in [path]/app/cache/dev/appDevDebugProjectContainer.php on line 1035

**Comment by farmatholin** [comment]
Thanks

**Comment by djardine** [comment]
thanks for the quick fix!
